#!/bin/bash
# Daily logical backup of all 8 BeeBase databases: pg_dump each, gzip,
# stream straight to S3 (never landing on local disk, so backups are
# never stored only on the EC2 instance). Runs via a systemd timer - see
# beebase-backup.timer/.service, installed once alongside deploy.sh.
#
# pg_dump runs inside each already-running postgres container via
# `docker compose exec`, authenticating over the container's local Unix
# socket (trusted for the container's own `beebase` role) - no database
# password needs to be known by this script.
set -euo pipefail

COMPOSE_DIR="/opt/beebase/compose"
CONFIG_DIR="/opt/beebase/config"
# deploy.env is the file Docker Compose's own ${VAR} interpolation reads
# for every postgres-*/migrate-* service (regenerated by deploy.sh on
# every deploy, so it's always current - see deploy.sh's header
# comment). The old shared .env this replaced is never updated as
# services are added and must not be used here.
ENV_FILE="${CONFIG_DIR}/deploy.env"
COMPOSE="docker compose -f ${COMPOSE_DIR}/docker-compose.prod.yml --env-file ${ENV_FILE}"

log() { echo "[backup $(date -u +%H:%M:%S)] $*"; }
fail() { echo "[backup $(date -u +%H:%M:%S)] ERROR: $*" >&2; exit 1; }

[ -f "${ENV_FILE}" ] || fail "${ENV_FILE} not found - has deploy.sh ever run successfully?"

# STORAGE_BUCKET is owned by media-service's own config (media.env), not
# deploy.env - see docker-compose.prod.yml's media-service entry and
# deploy/lib/env_config.sh's ENV_FILE_NAME[media].
MEDIA_ENV_FILE="${CONFIG_DIR}/media.env"
[ -f "${MEDIA_ENV_FILE}" ] || fail "${MEDIA_ENV_FILE} not found - has deploy.sh ever run successfully?"

S3_BACKUP_BUCKET=$(grep -m1 '^STORAGE_BUCKET=' "${MEDIA_ENV_FILE}" | cut -d= -f2-)
[ -n "${S3_BACKUP_BUCKET}" ] || fail "STORAGE_BUCKET not set in ${MEDIA_ENV_FILE}"

# Same IMDSv2 pattern as healthcheck-containers.sh's UnhealthyContainerCount
# metric, so this run's outcome is visible in CloudWatch instead of only in
# the local systemd journal - see terraform/modules/cloudwatch's
# backup_missing/backup_failed alarms.
IMDS_TOKEN=$(curl -fsS -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
AWS_REGION=$(curl -fsS -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" \
  http://169.254.169.254/latest/meta-data/placement/region)
INSTANCE_ID=$(curl -fsS -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" \
  http://169.254.169.254/latest/meta-data/instance-id)

# Best-effort: a transient CloudWatch API hiccup must never itself turn a
# genuinely successful backup run into a reported failure (or mask a real
# one) - the FAILURES count below is always the sole source of truth for
# this script's exit code.
publish_metric() {
  local metric_name="$1"
  aws cloudwatch put-metric-data \
    --region "${AWS_REGION}" \
    --namespace "BeeBase/Production" \
    --metric-name "${metric_name}" \
    --dimensions "InstanceId=${INSTANCE_ID}" \
    --value 1 \
    --unit Count \
    || log "WARNING: failed to publish ${metric_name} metric (backup result above is still authoritative)"
}

TIMESTAMP=$(date -u +%Y%m%dT%H%M%SZ)
FAILURES=0

# service -> database name
declare -A DATABASES=(
  [postgres-auth]=beebase_auth
  [postgres-apiary]=beebase_apiary
  [postgres-hive]=beebase_hive
  [postgres-inspection]=beebase_inspection
  [postgres-harvest]=beebase_harvest
  [postgres-media]=beebase_media
  [postgres-subscription]=beebase_subscription
  [postgres-notification]=beebase_notification
)

for svc in "${!DATABASES[@]}"; do
  db="${DATABASES[$svc]}"
  dest="s3://${S3_BACKUP_BUCKET}/postgres/${db}/${TIMESTAMP}.sql.gz"
  log "dumping ${db} (via ${svc}) -> ${dest}"

  # --expected-size is only needed above 50GB (AWS CLI default assumption
  # for a size-less stream) - nowhere near this deployment's dump sizes.
  if ${COMPOSE} exec -T "${svc}" pg_dump -U beebase "${db}" \
      | gzip \
      | aws s3 cp - "${dest}"; then
    log "ok: ${db}"
  else
    echo "[backup $(date -u +%H:%M:%S)] ERROR: backup failed for ${db}" >&2
    FAILURES=$((FAILURES + 1))
  fi
done

if [ "${FAILURES}" -gt 0 ]; then
  publish_metric BackupFailure
  fail "${FAILURES} of 8 database backups failed"
fi

publish_metric BackupSuccess
log "all 8 database backups completed successfully"
