# Release manifest parsing/validation, shared by deploy.sh and its tests
# (see deploy/tests/test_manifest.sh). Pure bash, no AWS/Docker calls -
# deliberately, so the "is this manifest even well-formed" question can
# be answered (and tested) without touching the network.
#
# A release manifest is a plain KEY=VALUE env file - see
# docker-compose.prod.yml's header comment for why there's one variable
# per service rather than a single shared IMAGE_TAG. It never contains
# secrets: only image tags plus the release identifier/timestamp. Source
# this file, then call manifest_parse <file> followed by
# manifest_validate; both print a clear reason to stderr and return
# non-zero on any problem, they never exit the calling shell themselves.

# One image-tag variable per application service - matches
# docker-compose.prod.yml exactly. gateway has no database/migration,
# statistics-service has no database either but still ships its own
# image, so all 9 are required in every release.
MANIFEST_SERVICE_TAG_KEYS=(
  GATEWAY_IMAGE_TAG
  AUTH_IMAGE_TAG
  APIARY_IMAGE_TAG
  HIVE_IMAGE_TAG
  INSPECTION_IMAGE_TAG
  HARVEST_IMAGE_TAG
  MEDIA_IMAGE_TAG
  STATISTICS_IMAGE_TAG
  SUBSCRIPTION_IMAGE_TAG
  NOTIFICATION_IMAGE_TAG
)

# Services whose migrate image (<tag>-migrate) deploy.sh must also run.
# statistics-service and gateway have no database, so no migrate image.
MANIFEST_MIGRATE_TAG_KEYS=(
  AUTH_IMAGE_TAG
  APIARY_IMAGE_TAG
  HIVE_IMAGE_TAG
  INSPECTION_IMAGE_TAG
  HARVEST_IMAGE_TAG
  MEDIA_IMAGE_TAG
  SUBSCRIPTION_IMAGE_TAG
  NOTIFICATION_IMAGE_TAG
)

MANIFEST_REQUIRED_KEYS=(RELEASE "${MANIFEST_SERVICE_TAG_KEYS[@]}")

# ECR repository name for each *_IMAGE_TAG key - used by deploy.sh to
# check image existence and to map service keys to ECR repos.
declare -gA MANIFEST_ECR_REPO=(
  [GATEWAY_IMAGE_TAG]=beebase-gateway
  [AUTH_IMAGE_TAG]=beebase-auth-service
  [APIARY_IMAGE_TAG]=beebase-apiary-service
  [HIVE_IMAGE_TAG]=beebase-hive-service
  [INSPECTION_IMAGE_TAG]=beebase-inspection-service
  [HARVEST_IMAGE_TAG]=beebase-harvest-service
  [MEDIA_IMAGE_TAG]=beebase-media-service
  [STATISTICS_IMAGE_TAG]=beebase-statistics-service
  [SUBSCRIPTION_IMAGE_TAG]=beebase-subscription-service
  [NOTIFICATION_IMAGE_TAG]=beebase-notification-service
)

# Populated by manifest_parse.
declare -gA MANIFEST=()

manifest_reset() {
  MANIFEST=()
}

# manifest_parse <file>
# Reads a KEY=VALUE manifest into the MANIFEST associative array. Blank
# lines and full-line "#" comments are allowed; anything else that isn't
# a clean KEY=VALUE pair, or a key repeated twice, is rejected - a
# release manifest is meant to be generated by exactly one thing (the
# release pipeline), so anything that doesn't parse cleanly is treated
# as corruption, not as something to guess around.
manifest_parse() {
  local file="$1"

  if [ -z "${file}" ]; then
    echo "manifest: no manifest file given" >&2
    return 1
  fi
  if [ ! -f "${file}" ]; then
    echo "manifest: '${file}' does not exist or is not a regular file" >&2
    return 1
  fi
  if [ ! -r "${file}" ]; then
    echo "manifest: '${file}' is not readable" >&2
    return 1
  fi

  manifest_reset

  local lineno=0 line key value
  while IFS= read -r line || [ -n "${line}" ]; do
    lineno=$((lineno + 1))

    # Trim trailing CR, in case the manifest was ever touched on Windows.
    line="${line%$'\r'}"

    [ -z "${line}" ] && continue
    [[ "${line}" =~ ^[[:space:]]*# ]] && continue

    if [[ ! "${line}" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      echo "manifest: ${file}:${lineno}: malformed line (expected KEY=VALUE): '${line}'" >&2
      return 1
    fi

    key="${BASH_REMATCH[1]}"
    value="${BASH_REMATCH[2]}"

    if [ -n "${MANIFEST[${key}]+set}" ]; then
      echo "manifest: ${file}:${lineno}: duplicate key '${key}'" >&2
      return 1
    fi

    MANIFEST[${key}]="${value}"
  done <"${file}"

  if [ "${#MANIFEST[@]}" -eq 0 ]; then
    echo "manifest: ${file} is empty" >&2
    return 1
  fi

  return 0
}

# manifest_validate
# Checks the already-parsed MANIFEST: every required key present, every
# image tag looks like a real Git commit SHA, and "latest" is always
# rejected regardless of what shape it's in. Call after manifest_parse.
manifest_validate() {
  local key tag

  for key in "${MANIFEST_REQUIRED_KEYS[@]}"; do
    if [ -z "${MANIFEST[${key}]+set}" ] || [ -z "${MANIFEST[${key}]}" ]; then
      echo "manifest: missing required key '${key}'" >&2
      return 1
    fi
  done

  # RELEASE is used verbatim in file paths (releases/<RELEASE>.env) and
  # CloudWatch log stream names - keep it to a safe, boring charset.
  if [[ ! "${MANIFEST[RELEASE]}" =~ ^[A-Za-z0-9._-]+$ ]]; then
    echo "manifest: RELEASE '${MANIFEST[RELEASE]}' contains characters other than [A-Za-z0-9._-]" >&2
    return 1
  fi

  for key in "${MANIFEST_SERVICE_TAG_KEYS[@]}"; do
    tag="${MANIFEST[${key}]}"

    if [ "${tag}" = "latest" ]; then
      echo "manifest: ${key}=latest is not allowed - use a real Git commit SHA" >&2
      return 1
    fi

    if [[ ! "${tag}" =~ ^[0-9a-f]{7,40}$ ]]; then
      echo "manifest: ${key}='${tag}' doesn't look like a Git commit SHA (expected 7-40 lowercase hex characters)" >&2
      return 1
    fi
  done

  return 0
}

# manifest_get <key> - convenience accessor, empty string if unset.
manifest_get() {
  printf '%s' "${MANIFEST[$1]-}"
}
