#!/bin/bash
# Unit tests for deploy/lib/manifest.sh - pure bash, no AWS/Docker
# involved, so these run anywhere (including CI) with nothing installed
# beyond bash itself.
set -uo pipefail

TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "${TESTS_DIR}")"
# shellcheck source=../lib/manifest.sh
source "${DEPLOY_DIR}/lib/manifest.sh"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

PASS=0
FAIL=0

# assert_fail <description> <manifest-content>
# Writes the manifest, expects parse+validate to fail.
assert_fail() {
  local desc="$1" content="$2" file="${TMP_DIR}/m.env"
  printf '%s' "${content}" >"${file}"
  if manifest_parse "${file}" >/dev/null 2>&1 && manifest_validate >/dev/null 2>&1; then
    echo "FAIL: ${desc} (expected rejection, but manifest was accepted)"
    FAIL=$((FAIL + 1))
  else
    echo "PASS: ${desc}"
    PASS=$((PASS + 1))
  fi
}

valid_manifest() {
  cat <<'EOF'
RELEASE=2026.09.07-1
CREATED_AT=2026-09-07T18:00:00Z
GATEWAY_IMAGE_TAG=5a066d9aa5a066d9aa5a066d9aa5a066d9aa5a06
AUTH_IMAGE_TAG=0b4d246bb0b4d246bb0b4d246bb0b4d246bb0b4d
APIARY_IMAGE_TAG=436efffcc436efffcc436efffcc436efffcc436
HIVE_IMAGE_TAG=f9e257addf9e257addf9e257addf9e257addf9e
INSPECTION_IMAGE_TAG=8844c5bee8844c5bee8844c5bee8844c5bee8844
MEDIA_IMAGE_TAG=a5b903bffa5b903bffa5b903bffa5b903bffa5b9
STATISTICS_IMAGE_TAG=a0877a011a0877a011a0877a011a0877a011a08
SUBSCRIPTION_IMAGE_TAG=b85447100b85447100b85447100b85447100b854
EOF
}

# --- 1. missing manifest (no file given) ---

if manifest_parse "" >/dev/null 2>&1; then
  echo "FAIL: missing manifest path is rejected"
  FAIL=$((FAIL + 1))
else
  echo "PASS: missing manifest path is rejected"
  PASS=$((PASS + 1))
fi

# --- 2. manifest file that doesn't exist ---

if manifest_parse "${TMP_DIR}/does-not-exist.env" >/dev/null 2>&1; then
  echo "FAIL: nonexistent manifest file is rejected"
  FAIL=$((FAIL + 1))
else
  echo "PASS: nonexistent manifest file is rejected"
  PASS=$((PASS + 1))
fi

# --- 3. malformed manifest (not KEY=VALUE) ---

assert_fail "malformed line is rejected" "$(cat <<'EOF'
RELEASE=2026.09.07-1
this is not a key=value line
GATEWAY_IMAGE_TAG=5a066d9aa5a066d9aa5a066d9aa5a066d9aa5a06
EOF
)"

# --- 4. malformed manifest (duplicate key) ---

assert_fail "duplicate key is rejected" "$(cat <<'EOF'
RELEASE=2026.09.07-1
RELEASE=2026.09.07-2
GATEWAY_IMAGE_TAG=5a066d9aa5a066d9aa5a066d9aa5a066d9aa5a06
EOF
)"

# --- 5. missing a required service tag (auth-service absent) ---

assert_fail "missing AUTH_IMAGE_TAG is rejected" "$(cat <<'EOF'
RELEASE=2026.09.07-1
GATEWAY_IMAGE_TAG=5a066d9aa5a066d9aa5a066d9aa5a066d9aa5a06
APIARY_IMAGE_TAG=436efffcc436efffcc436efffcc436efffcc436
HIVE_IMAGE_TAG=f9e257addf9e257addf9e257addf9e257addf9e
INSPECTION_IMAGE_TAG=8844c5bee8844c5bee8844c5bee8844c5bee8844
MEDIA_IMAGE_TAG=a5b903bffa5b903bffa5b903bffa5b903bffa5b9
STATISTICS_IMAGE_TAG=a0877a011a0877a011a0877a011a0877a011a08
EOF
)"

# --- 6. invalid SHA (too short / non-hex) ---

assert_fail "non-hex image tag is rejected" "$(valid_manifest | sed 's/^AUTH_IMAGE_TAG=.*/AUTH_IMAGE_TAG=not-a-sha!/')"
assert_fail "too-short image tag is rejected" "$(valid_manifest | sed 's/^AUTH_IMAGE_TAG=.*/AUTH_IMAGE_TAG=abc123/')"

# --- 7. "latest" is always rejected ---

assert_fail "'latest' tag is rejected" "$(valid_manifest | sed 's/^AUTH_IMAGE_TAG=.*/AUTH_IMAGE_TAG=latest/')"

# --- 8. RELEASE with unsafe characters ---

assert_fail "RELEASE with a slash is rejected" "$(valid_manifest | sed 's#^RELEASE=.*#RELEASE=2026/09/07-1#')"
assert_fail "RELEASE with whitespace is rejected" "$(valid_manifest | sed 's/^RELEASE=.*/RELEASE=2026 09 07-1/')"

# --- 9. empty manifest file ---

assert_fail "empty manifest is rejected" ""

# --- 10. successful parse + validate of a well-formed manifest ---

VALID_FILE="${TMP_DIR}/valid.env"
valid_manifest >"${VALID_FILE}"
if manifest_parse "${VALID_FILE}" && manifest_validate; then
  echo "PASS: well-formed manifest parses and validates"
  PASS=$((PASS + 1))
  if [ "$(manifest_get RELEASE)" = "2026.09.07-1" ] && [ "$(manifest_get AUTH_IMAGE_TAG)" = "0b4d246bb0b4d246bb0b4d246bb0b4d246bb0b4d" ]; then
    echo "PASS: parsed values are retrievable via manifest_get"
    PASS=$((PASS + 1))
  else
    echo "FAIL: parsed values are retrievable via manifest_get"
    FAIL=$((FAIL + 1))
  fi
else
  echo "FAIL: well-formed manifest parses and validates"
  FAIL=$((FAIL + 2))
fi

# --- 11. comments and blank lines are ignored ---

COMMENTED_FILE="${TMP_DIR}/commented.env"
{
  echo "# release manifest, generated by the release pipeline"
  echo ""
  valid_manifest
  echo ""
} >"${COMMENTED_FILE}"
if manifest_parse "${COMMENTED_FILE}" && manifest_validate; then
  echo "PASS: comments and blank lines are ignored"
  PASS=$((PASS + 1))
else
  echo "FAIL: comments and blank lines are ignored"
  FAIL=$((FAIL + 1))
fi

echo
echo "manifest.sh tests: ${PASS} passed, ${FAIL} failed"
[ "${FAIL}" -eq 0 ]
